apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elasticsearch.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "elasticsearch.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "elasticsearch.fullname" . }}
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.image }}
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          emptyDir: {}