apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash.fullname" . }}-config
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://{{ .Release.Name }}-elasticsearch:9200"]
        index => "bank-logs-%{+YYYY.MM.dd}"
      }
    
      stdout { codec => rubydebug }
    }