apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
data:
  KEYCLOAK_ISSUER_URI: {{ .Values.global.keycloakIssuerUri | quote }}
  CASH_SERVICE_URL: {{ .Values.routes.cashServiceUrl | quote }}
  TRANSFER_SERVICE_URL: {{ .Values.routes.transferServiceUrl | quote }}
  ACCOUNTS_SERVICE_URL: {{ .Values.routes.accountsServiceUrl | quote }}
  TRACE_PROBABILITY: {{ .Values.tracing.probability | quote }}
  ZIPKIN_ENDPOINT: "http://{{ .Release.Name }}-zipkin.{{ .Release.Namespace }}.svc.cluster.local:9411/api/v2/spans"
  LOGGING_LOGSTASH_DESTINATION: "{{ .Release.Name }}-logstash:5044"
