spring:
  application:
    name: accounts-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: ${TRACE_PROBABILITY}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  metrics:
    distribution:
      percentiles-precision:
        http.server.requests: 2
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99