apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-controller.fullname" . }}-config
data:
  KEYCLOAK_ISSUER_URI: {{ .Values.global.keycloakIssuerUri | quote }}
  API_GATEWAY_URL: {{ .Values.config.apiGatewayUrl | quote }}
  TRACE_PROBABILITY: {{ .Values.tracing.probability | quote }}
  ZIPKIN_ENDPOINT: "http://{{ .Release.Name }}-zipkin.{{ .Release.Namespace }}.svc.cluster.local:9411/api/v2/spans"
