server:
  port: ${SERVER_PORT:8084}
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/realms/my-bank}
      client:
        client:
          provider:
            keycloak:
              issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/realms/my-bank}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin-service:9411/api/v2/spans"
mybank:
  clients:
    accounts-service:
      base-url: ${API_GATEWAY_URL:http://localhost:8080}
    transfer-service:
      base-url: ${API_GATEWAY_URL:http://localhost:8080}
    cash-service:
      base-url: ${API_GATEWAY_URL:http://localhost:8080}