spring:
  application:
    name: front-controller
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          keycloak:
            client-id: front-ui
            authorization-grant-type: authorization_code
            scope: openid,profile,email
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: ${TRACE_PROBABILITY}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
mybank:
  clients:
    accounts-service:
      base-url: ${API_GATEWAY_URL}
    transfer-service:
      base-url: ${API_GATEWAY_URL}
    wallet-service:
      base-url: ${API_GATEWAY_URL}